version: 2.1
<<<<<<< HEAD

  jobs:
    build:
      docker:
        - image: circleci/node@5.1.0
      steps:
        - checkout
        - run: npm install
        - run: npm test
=======
orbs:
  node: circleci/node@18.12.1
workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
>>>>>>> 6c70f6e22c8736068c8766ed4ebceac4d817e1a1
