# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
orbs:
  node: circleci/node@18.12.1

#jobs:
#  test:
#    docker:
#      - image: circleci/node:18.12.1

jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests


    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    #steps:
    #  - checkout
    #  - run : npm install
    #  - run : npm test

