version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
       - image: circleci/node@18.12.1
    steps:
      - checkout
      - run: npm install 
      - run: npm test